### ISSUE TITLE
Learn App Will Not Open Current Lesson 

### ISSUE THREAD

**Issue by lucy007** [learn-co-curriculum/say-hello-ruby#15]
Hello,

I skipped over some lessons on my Mac to see other topics to be covered and had this pop up message...

- (We strongly encourage you to complete lessons in sequence, but you can jump ahead if you're sure you want to proceed. You can always come back and finish this lesson later) -

I was working on the "Introductory Default Arguments 1" lesson, but Learn will not go back to that topic/lab I started. So, again I skipped ahead to the last topic, hoping it'll start from the beginning and reset Learn, still no changes, it's stuck on the last lesson. Please, how can I resolve.

Kind Regards,
Lucy

**Comment by AnnJohn** [comment]
hi @lucy007 can you use the Ask a Question tool if this is still an issue since we use this space for issues specifically related to curriculum content. 

Typically though once you complete a lab, that will be your default spot so you may have to click next to complete a lab and then you might be set.
