### ISSUE TITLE
Introductory Default Arguments I - Suggestion

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/say-hello-ruby#9]
I found that the instructions for this lab were rather nebulous and/or inexplicit. Perhaps this is because more is expected of us students with more exposure to Ruby methods and arguments and hand-holding is occurring less.

I think that this lab should reference objective 2 of the previous Methods and Arguments exercise because that exercise helped me get through this lab. 

Consider this code:
```
    def arguments_and_local_variables(name)
      person = name
      "Hello " + person
    end

    arguments_and_local_variables("George R.R. Martin")
      #=> "Hello George R.R. Martin"
```

I found the above very useful in understanding the instructions in *Introductory Default Arguments I* because using the plus sign is a big part of creating a method that satisfies the lab's requirements *(Introductory Default Arguments I)* especially when you need your code to look like this to pass the lab: 
```
def say_hello(name = "Ruby Programmer")
  puts "Hello " + name + "!"
end
```

(note the "+") Take a look and tell me what you think I would love to answer any questions.

**Comment by AnnJohn** [comment]
@m00se333 Thanks for raising the issue. Yes, we definitely want students to be able to make their own connections between lessons and where information is provided across lessons. So you're right- we try to do less hand holding as we move along. 

We actually love that you were able to go back to a previous lesson to realize the missing piece you needed to make the method work for you, and feel that because you did that and had to critically think through this, you'll better retain this information rather than if it were laid out explicitly for you.

That being said, if you feel like instructions are just plain confusing, you can feel free to make a suggestion (using the Suggest a Change function in Learn) and one of our instructors will review and decide whether to add it or not. We, however, avoid linking or referencing to earlier lessons or labs in our content since lessons can be used in multiple tracks so that's something to keep in mind.

Thanks and happy to answer any questions
